name: Test Cluster Connection

on:
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: self-hosted-local
    steps:
      # Resuse our shared workflow
      - name: 🔧 Setup kubectl
        uses: OpenCloudHub/.github/.github/actions/setup-kubectl@main
        with:
          kube-config: ${{ secrets.KUBE_CONFIG }}

      - name: Check kubectl access
        run: |
          kubectl cluster-info
          kubectl get nodes
          kubectl get namespaces
